name: KariClaims
version: '1.0-SNAPSHOT'
main: org.kari.kariClaims.KariClaims
api-version: '1.21'
authors: [ kari ]
description: 高性能领地保护插件，兼容 UltimateClaims

commands:
  claim:
    description: 领地管理主命令
    usage: /<command> [参数]
    aliases: [c]
  kariclaims:
    description: KariClaims 管理命令
    usage: /<command> migrate <source>
    permission: kariclaims.admin.migrate

permissions:
  kariClaims.*:
    description: 所有权限
    default: op
    children:
      kariClaims.use: true
      kariClaims.admin: true
      kariClaims.bypass: true
  kariClaims.use:
    description: 使用领地功能
    default: true
  kariClaims.claim:
    description: 认领区块
    default: true
  kariClaims.unclaim:
    description: 取消认领
    default: true
  kariClaims.home:
    description: 传送到home
    default: true
  kariClaims.sethome:
    description: 设置home
    default: true
  kariClaims.accept:
    description: 接受邀请
    default: true
  kariClaims.ban:
    description: 封禁玩家
    default: true
  kariClaims.unban:
    description: 解封玩家
    default: true
  kariClaims.dissolve:
    description: 解散领地
    default: true
  kariClaims.invite:
    description: 邀请玩家
    default: true
  kariClaims.kick:
    description: 踢出玩家
    default: true
  kariClaims.leave:
    description: 离开领地
    default: true
  kariClaims.lock:
    description: 锁定领地
    default: true
  kariClaims.recipe:
    description: 查看配方
    default: true
  kariClaims.name:
    description: 重命名领地
    default: true
  kariClaims.transfer:
    description: 转移领地
    default: true
  kariclaims.list:
    description: 列出自己的领地
    default: true
  kariClaims.admin:
    description: 管理员权限
    default: op
    children:
      kariClaims.admin.bypass: true
      kariClaims.admin.rename: true
      kariClaims.admin.unlock: true
      kariClaims.admin.removeclaim: true
      kariClaims.admin.transfer: true
      kariClaims.admin.nolog: true
      kariclaims.admin.list: true
      kariClaims.admin.invisible: true
  kariClaims.admin.bypass:
    description: 绕过所有领地保护
    default: op
  kariClaims.admin.rename:
    description: 强制重命名领地
    default: op
  kariClaims.admin.unlock:
    description: 强制锁定/解锁领地
    default: op
  kariClaims.admin.removeclaim:
    description: 强制删除领地
    default: op
  kariClaims.admin.transfer:
    description: 强制转移领地
    default: op
  kariClaims.bypass:
    description: 绕过领地限制
    default: op
    children:
      kariClaims.bypass.lock: true
      kariClaims.bypass.ban: true
      kariClaims.bypass.fly: true
      kariClaims.bypass.home: true
      kariClaims.bypass.perms: true
  kariClaims.bypass.lock:
    description: 进入已锁定的领地
    default: op
  kariClaims.bypass.ban:
    description: 进入已被封禁的领地
    default: op
  kariClaims.bypass.fly:
    description: 在领地内飞行
    default: op
  kariClaims.bypass.home:
    description: 前往任意领地的家
    default: op
  kariClaims.powercell.view:
    description: 查看任何能量电池
    default: op
  kariclaims.admin.list:
    description: 查看其他玩家的领地列表
    default: op
  kariclaims.admin.migrate:
    description: 从其他插件迁移数据
    default: op
