name: AkiAsync
version: 3.2.7-SNAPSHOT
main: org.virgil.akiasync.AkiAsyncPlugin
api-version: 1.21
folia-supported: true
authors: [virgil698, AnkiSama]
description: Async optimizations for Paper server - Entity Tracker & More

commands:
  aki-reload:
    description: Reloads the plugin configuration
    permission: akiasync.admin
  aki-debug:
    description: Debug command for development
    permission: akiasync.admin
  aki-version:
    description: Shows the plugin version
    permission: akiasync.admin

